# Generated by Django 5.0 on 2026-01-31 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('readiness', 'Readiness Analysis'), ('gender', 'Gender Gap Analysis'), ('discipline', 'Discipline Analysis'), ('satisfaction', 'Satisfaction Report'), ('comprehensive', 'Comprehensive Report')], max_length=50)),
                ('description', models.TextField()),
                ('methodology', models.TextField()),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('statistical_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_type', models.CharField(choices=[('kruskal_wallis', 'Kruskal-Wallis H-test'), ('mann_whitney', 'Mann-Whitney U-test'), ('chi_square', 'Chi-Square Test'), ('anova', 'ANOVA')], max_length=50)),
                ('variables_tested', models.CharField(max_length=200)),
                ('test_statistic', models.FloatField()),
                ('p_value', models.FloatField()),
                ('significance_level', models.FloatField(default=0.05)),
                ('is_significant', models.BooleanField()),
                ('interpretation', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistical_tests', to='analytics.analyticalreport')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('survey_type', models.CharField(choices=[('readiness', 'AI Readiness'), ('satisfaction', 'Satisfaction'), ('relevance', 'Relevance Perception'), ('feedback', 'General Feedback')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='analytics.surveytemplate')),
            ],
            options={
                'unique_together': {('survey', 'respondent')},
            },
        ),
    ]
